#!/bin/sh

umask 022

PHPRC="{$PHP_STARTER_DIR}/{$DOMAIN_NAME}/php/"
export PHPRC

PHP_FCGI_CHILDREN=2
export PHP_FCGI_CHILDREN

PHP_FCGI_MAX_REQUESTS=500
export PHP_FCGI_MAX_REQUESTS

TMPDIR="{$GUI_ROOT_DIR}/phptmp"
export TMPDIR

exec {$PHP_FASTCGI_BIN}
